### ISSUE TITLE
specific variables per remote target

### ISSUE THREAD

**Issue by JuanMoroteP** [FherStk/AutoCheck#58]
In some cases you expect different outputs depending the remote target, so you need to specify in each remote the specific value that will be consider correct.  

somenthing like:
  - remote: 
      - os: GNU
      - host: ip_host_1
      - user: user_remote_1
      - password: pass_remote_1
      - vars:
                sol1: solution1_remote_1
                sol2: solution2_remote_1

**Comment by FherStk** [comment]
Consider it done :)

**Comment by FherStk** [comment]
Just released (v2.6.0).
Please, test it and provide me some feedback in order to update my internal tests if something fails.
